"""stage6_layout_skeleton.py — Generate JSX page skeletons (no LLM needed)."""

import re


def _to_pascal(s: str) -> str:
    return re.sub(r"[-_\s]+(.)", lambda m: m.group(1).upper(), s).capitalize()


def generate_skeleton(layout: dict, components: dict, design: dict) -> dict[str, str]:
    """Return {page_name: jsx_skeleton_string} for all pages."""
    p          = design["palette"]
    primary    = p["primary"].split("-")[0]
    dark_bg    = f"bg-{p['bg']}"
    effect     = design.get("visual_effect", "corner-blur")
    placement  = design.get("effect_placement", "top-right")

    placement_classes = {
        "top-right":    "top-0 right-0",
        "top-left":     "top-0 left-0",
        "bottom-right": "bottom-0 right-0",
        "bottom-left":  "bottom-0 left-0",
    }.get(placement, "top-0 right-0")

    skeletons: dict[str, str] = {}

    for page in layout["pages"]:
        page_name  = page["name"]
        page_comps = components["component_map"].get(page_name, page.get("components", []))
        pascal     = _to_pascal(page_name)

        imports = "\n".join(
            f"import {{ {_to_pascal(c)} }} from './components/{_to_pascal(c)}';"
            for c in page_comps
        )

        usage = "\n".join(f"      <{_to_pascal(c)} />" for c in page_comps)

        blur_jsx = ""
        if effect != "none":
            blur_jsx = (
                f'      {{/* Visual accent — {placement} */}}\n'
                f'      <div className="absolute {placement_classes} w-96 h-96 '
                f'bg-{primary}-500/20 blur-3xl rounded-full pointer-events-none" />'
            )

        skeletons[page_name] = f"""\
// {page_name}.jsx — Generated by Prompt Machine v3.0
// Page type: {page['type']} | Route: {page.get('route', '/')}
{imports}

export default function {pascal}Page() {{
  return (
    <div className="relative min-h-screen {dark_bg}">
{blur_jsx}
{usage}
    </div>
  );
}}
"""

    return skeletons
