// Quiz Selection.jsx — Generated by Prompt Machine v3.0
// Page type: list | Route: /quiz-selection
import { Navbar } from './components/Navbar';
import { Hero } from './components/Hero';
import { Cards } from './components/Cards';
import { Footer } from './components/Footer';

export default function QuizselectionPage() {
  return (
    <div className="relative min-h-screen bg-white">

      <Navbar />
      <Hero />
      <Cards />
      <Footer />
    </div>
  );
}
