// Quiz Player.jsx — Generated by Prompt Machine v3.0
// Page type: detail | Route: /quiz-player/:quizId
import { Navbar } from './components/Navbar';
import { Hero } from './components/Hero';
import { Cards } from './components/Cards';
import { Footer } from './components/Footer';

export default function QuizplayerPage() {
  return (
    <div className="relative min-h-screen bg-white">

      <Navbar />
      <Hero />
      <Cards />
      <Footer />
    </div>
  );
}
